### ISSUE TITLE
【依頼】フリマアプリの挙動確認

### ISSUE THREAD

**Issue by potato972** [potato972/furima-36681#22]
#URL
https://furima-36681.herokuapp.com/

#IDとパスワード
ID                  560923645109
パスワード   !uB_5ZIIK(PNj7$

#ユーザー情報1
aaabbbccc@gmail.com
abcdefg1
#ユーザー情報2
cccbbbaaa@gmail.com
abcdefg2

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたBasic認証のIDとパスワードを入力すると、最終課題アプリ（FURIMA）のトップページ（商品一覧ページ）が表示されるようにしましょう**
記載いただいたIDとパスワードでBasic認証が突破できませんでした。
ID：admin　パスワード：2222が正しい情報ではないでしょうか。設定したBasic認証のIDとパスワードをコメントに記載いただくようお願いいたします。

- [ ] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されるようにしましょう（--- は初期値として設定すること）**
「本・音楽・ゲーム」は1項目にしましょう。
<img width="320" alt="スクリーンショット_2022-02-04_9_17_39" src="https://user-images.githubusercontent.com/62644781/152451021-8a815853-ed60-4a2f-851b-d78aef53830e.png">

- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるようにしましょう（--- は初期値として設定すること）**
「都・府・県」が抜けているので修正しましょう。

- [ ] **出品ページにて、エラーハンドリングの際、重複したエラーメッセージが表示されないようにしましょう**
以下のエラーメッセージが重複しております。
<img width="320" alt="スクリーンショット_2022-02-04_9_12_48" src="https://user-images.githubusercontent.com/62644781/152450651-a280e6fe-da29-4a07-9304-e0b842786360.png">

- [ ] **編集ページにて、エラーハンドリングの際、重複したエラーメッセージが表示されないようにしましょう**
以下のエラーメッセージが重複しております。
<img width="320" alt="スクリーンショット_2022-02-04_9_08_40" src="https://user-images.githubusercontent.com/62644781/152450730-82d65f3d-6545-4d56-b19a-69f9c15d32ac.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by potato972** [comment]
確認ありがとうございました。
ID: admin
password: 2222
失礼しました。

修正しました。確認お願いいたします。

**Comment by mo1015** [comment]
フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6853

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/152483264-9016151b-7856-4458-8af6-d17cce3d7c56.png)
